version: "3.9"
networks:
  renting-dev:
    driver: bridge
services:
  app: 
    container_name: deploy-guide
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - renting-dev
    depends_on:
      - postgres_db
  postgres_db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: Renting
    ports:
      - "5432:5432"
    networks:
      - renting-dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: